pub const COLOR: &[&str] = &[
    "red",
    "green",
    "yellow",
    "purple",
    "blue",
    "violet",
    "luminous",
    "dull",
    "grey",
    "vibrant",
    "scarlet",
    "crimson",
    "amber",
    "emerald",
    "sapphire",
    "turquoise",
    "indigo",
    "azure",
    "bronze",
    "silver",
    "golden",
    "copper",
    "ashen",
    "pale",
    "glowing",
    "bright",
    "faded",
    "dark",
    "brilliant",
    "iridescent",
    "gleaming",
    "translucent",
    "opaque",
    "radiant",
    "shimmering",
    "glittering",
    "glossy",
    "matte",
    "polished",
    "tarnished",
];

pub const SIZE_SHAPE: &[&str] = &[
    "large",
    "small",
    "wide",
    "mishappen",
    "person-sized",
    "giant",
    "teeny-tiny",
    "miniscule",
    "broad",
    "skinny",
];

pub const NATURAL_FOOD: &[&str] = &[
    "carrot",
    "potato",
    "piece of bark",
    "turnip",
    "coconut",
    "apple",
    "berry",
    "root",
    "lemon",
    "orange",
    "honey",
    "sprout",
    "pepper",
    "grain",
    "shoot",
    "nettles",
    "spinach",
    "acorn",
    "strawberry",
    "blueberry",
    "walnut",
    "hazelnut",
    "artichoke",
    "onion",
];

pub const NATURAL_WATER_SOURCE: &[&str] = &[
    "puddle",
    "spring",
    "brook",
    "old well",
    "creek",
    "waterhole",
    "run",
    "rill",
    "seep",
];

pub const QUALITY_WATER_SOURCE_QUALIFIER: &[&str] =
    &["clear", "cyan", "pristine", "pure", "untainted"];

pub const DUBIOUS_WATER_SOURCE_QUALIFIER: &[&str] = &[
    "muddy",
    "cloudy",
    "dirty",
    "vibrant green",
    "vibrant pink",
    "mosquito-ridden",
];

pub const DUBIOUS_FOOD_QUALIFIER: &[&str] = &[
    "putrid",
    "smelly",
    "glowing",
    "mushy",
    "gross",
    "ordinary",
    "suspicious",
    "unnatural",
    "moldy",
];

pub const POSSIBLY_POISONOUS_FOOD: &[&str] = &[
    "mushroom",
    "fungus",
    "discarded meat",
    "carcass",
    "flower",
    "fruit",
    "leaf",
    "morel",
    "chanterelles",
    "porcini",
];

pub const FISH: &[&str] = &[
    "crayfish",
    "haddock",
    "salmon",
    "snails",
    "bass",
    "mackerel",
    "cod",
    "sardine",
    "barracuda",
    "snapper",
    "herring",
    "squid",
    "cuttlefish",
    "lobster",
    "prawn",
    "oyster",
    "lionfish",
    "sunfish",
    "triggerfish",
    "sturgeon",
    "surgeonfish",
    "parrotfish",
    "swordfish",
    "sailfish",
    "merlin",
    "pufferfish",
];

pub const NATURAL_SHELTER: &[&str] = &[
    "cave",
    "cavern",
    "grotto",
    "rocky overhang",
    "rocky alcove",
    "hollow tree",
    "hollow trunk",
    "large boulder",
    "dense thicket",
    "large tree",
    "dirt embankment",
];
